import { useEffect, useState, type FormEvent } from 'react';
type Props = { api: (path: string, options?: RequestInit) => Promise<any>; profile: any; onBack: () => void };
export function AdminDealHub({ api, profile, onBack }: Props) {
  const [deals, setDeals] = useState<any[]>([]); const [active, setActive] = useState<any>(null); const [creating, setCreating] = useState(false); const [notice, setNotice] = useState('');
  const load = () => api('/api/deals').then(items => { setDeals(items); const requested = new URLSearchParams(window.location.search).get('deal'); if (requested) setActive(items.find((item: any) => item.id === requested) || null); }).catch(reason => setNotice((reason as Error).message));
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const deal = await api('/api/admin/private-deals', { method: 'POST', body: JSON.stringify({ description: form.get('description'), amount: form.get('amount') || 0, currency: form.get('currency') || 'USD' }) }); setDeals(items => [deal, ...items]); setActive(deal); } catch (reason) { setNotice((reason as Error).message); } }
  if (active) return <AdminRoom api={api} profile={profile} deal={active} onBack={() => { setActive(null); void load(); }} />;
  return <main className="dashboard private-deals"><header className="app-top"><button onClick={onBack}>‹</button><div className="top-brand"><span>🛡️</span><strong>Admin Escrow</strong></div><button onClick={() => setCreating(true)}>＋</button></header><section className="deal-intro"><span>OFFICIAL ADMINISTRATOR</span><h1>Escrow control center</h1><p>Create administrator-led rooms and invite both buyer and seller.</p><button onClick={() => setCreating(true)}>Create admin room</button></section>{creating && <form className="room-form" onSubmit={create}><h2>Create admin-led room</h2><label>Deal description<textarea name="description" minLength={10} required placeholder="Describe the item, terms, and escrow instructions." /></label><div className="room-form-row"><label>Amount<input name="amount" type="number" min="0" step="0.01" /></label><label>Currency<input name="currency" defaultValue="USD" /></label></div><button>Create room</button></form>}<section className="deal-list"><h2>All deal rooms</h2>{deals.map(deal => <button className="deal-preview" key={deal.id} onClick={() => setActive(deal)}><span>🛡️</span><div><b>{deal.item}</b><p>{deal.buyer?.nickname || 'Buyer pending'} · {deal.seller?.nickname || 'Seller pending'}</p></div><i>›</i></button>)}</section>{notice && <p className="error">{notice}</p>}</main>;
}
function AdminRoom({ api, profile, deal, onBack }: { api: Props['api']; profile: any; deal: any; onBack: () => void }) {
  const [nickname, setNickname] = useState(''); const [role, setRole] = useState<'BUYER' | 'SELLER'>('BUYER'); const [messages, setMessages] = useState<any[]>([]); const [draft, setDraft] = useState(''); const [notice, setNotice] = useState('');
  const load = () => api(`/api/deals/${deal.id}/messages`).then(setMessages).catch(reason => setNotice((reason as Error).message));
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 4000); return () => clearInterval(timer); }, [deal.id]);
  async function invite(event: FormEvent) { event.preventDefault(); try { await api(`/api/admin/deals/${deal.id}/invite`, { method: 'POST', body: JSON.stringify({ nickname, role }) }); setNotice(`@${nickname} was invited as the ${role.toLowerCase()}.`); setNickname(''); } catch (reason) { setNotice((reason as Error).message); } }
  async function send(event: FormEvent) { event.preventDefault(); if (!draft.trim()) return; try { const message = await api(`/api/deals/${deal.id}/messages`, { method: 'POST', body: JSON.stringify({ message: draft }) }); setMessages(items => [...items, message]); setDraft(''); } catch (reason) { setNotice((reason as Error).message); } }
  return <main className="dashboard deal-room"><header className="app-top"><button onClick={onBack}>‹</button><div className="top-brand"><span>🛡️</span><strong>Official Admin Room</strong></div></header><section className="deal-room-summary"><b>{deal.buyer?.nickname || 'Buyer pending'} ↔ {deal.seller?.nickname || 'Seller pending'}</b><p>{deal.terms}</p></section><section className="room-actions"><form onSubmit={invite}><select value={role} onChange={event => setRole(event.target.value as 'BUYER' | 'SELLER')}><option value="BUYER">Invite buyer</option><option value="SELLER">Invite seller</option></select><input value={nickname} onChange={event => setNickname(event.target.value)} placeholder="CL-Service username" required /><button>Invite</button></form></section><section className="private-message-list">{messages.map(message => <article className={message.sender.nickname === profile.nickname ? 'mine' : ''} key={message.id}><b>{message.sender.role === 'SUPER_ADMIN' ? '🛡️ Official Admin' : message.sender.nickname}</b><p>{message.body}</p></article>)}</section><form className="chat-composer" onSubmit={send}><input value={draft} onChange={event => setDraft(event.target.value)} placeholder="Write a message" /><button>Send</button></form>{notice && <p className={notice.includes('invited') ? 'success-note' : 'error'}>{notice}</p>}</main>;
}
