import { useEffect, useState, type FormEvent } from 'react';

const fiat = 'AED AFN ALL AMD ANG AOA ARS AUD AWG AZN BAM BBD BDT BGN BHD BIF BMD BND BOB BOV BRL BSD BTN BWP BYN BZD CAD CDF CHE CHF CHW CLF CLP CNY COP COU CRC CUC CUP CVE CZK DJF DKK DOP DZD EGP ERN ETB EUR FJD FKP GBP GEL GHS GIP GMD GNF GTQ GYD HKD HNL HRK HTG HUF IDR ILS INR IQD IRR ISK JMD JOD JPY KES KGS KHR KMF KPW KRW KWD KYD KZT LAK LBP LKR LRD LSL LYD MAD MDL MGA MKD MMK MNT MOP MRU MUR MVR MWK MXN MXV MYR MZN NAD NGN NIO NOK NPR NZD OMR PAB PEN PGK PHP PKR PLN PYG QAR RON RSD RUB RWF SAR SBD SCR SDG SEK SGD SHP SLE SLL SOS SRD SSP STN SVC SYP SZL THB TJS TMT TND TOP TRY TTD TWD TZS UAH UGX USD USN UYI UYU UYW UZS VED VES VND VUV WST XAF XCD XDR XOF XPF XSU XUA YER ZAR ZMW ZWG'.split(' ');
const crypto = ['BTC', 'ETH', 'USDT', 'USDC', 'BNB', 'SOL', 'XRP', 'ADA', 'DOGE', 'TRX', 'LTC', 'BCH', 'XMR', 'TON'];
type Props = { api: (path: string, options?: RequestInit) => Promise<any>; profile: any; onBack: () => void };

export function DealRoomHub({ api, profile, onBack }: Props) {
  const [deals, setDeals] = useState<any[]>([]); const [active, setActive] = useState<any>(null); const [newRoom, setNewRoom] = useState(false); const [notice, setNotice] = useState('');
  const load = () => api('/api/deals').then(setDeals).catch(reason => setNotice((reason as Error).message));
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const deal = await api('/api/private-deals', { method: 'POST', body: JSON.stringify({ role: form.get('role'), description: form.get('description'), amount: form.get('amount') || 0, currency: form.get('currency') }) }); setDeals(items => [deal, ...items]); setActive(deal); setNewRoom(false); } catch (reason) { setNotice((reason as Error).message); } }
  if (active) return <Room api={api} profile={profile} deal={active} onBack={() => { setActive(null); void load(); }} />;
  return <main className="dashboard private-deals"><header className="app-top"><button onClick={onBack}>‹</button><div className="top-brand"><span>🛡️</span><strong>Private Deals</strong></div><button onClick={() => setNewRoom(true)}>＋</button></header><section className="deal-intro"><span>OFFICIAL ESCROW</span><h1>Private deal rooms</h1><p>Create a room, invite the other participant, then invite the official administrator.</p><button onClick={() => setNewRoom(true)}>Create room</button></section>{newRoom && <form className="room-form" onSubmit={create}><h2>Create private room</h2><label>Your role<select name="role" defaultValue={profile.marketplaceRole}><option value="BUYER">Buyer</option><option value="SELLER">Seller</option></select></label><label>Deal description<textarea name="description" minLength={10} maxLength={2000} required placeholder="Describe the item or service and agreed terms." /></label><div className="room-form-row"><label>Amount (optional)<input name="amount" type="number" min="0" step="0.01" /></label><label>Currency / crypto<select name="currency" defaultValue="USD"><optgroup label="Fiat currencies">{fiat.map(code => <option value={code} key={code}>{code}</option>)}</optgroup><optgroup label="Cryptocurrency">{crypto.map(code => <option value={code} key={code}>{code}</option>)}</optgroup></select></label></div><div><button type="button" className="secondary" onClick={() => setNewRoom(false)}>Cancel</button><button>Create room</button></div></form>}<section className="deal-list"><h2>Your deal rooms</h2>{deals.length ? deals.map(deal => <button className="deal-preview" key={deal.id} onClick={() => setActive(deal)}><span>🛡️</span><div><b>{deal.item}</b><p>{deal.buyer?.nickname || 'Buyer pending'} · {deal.seller?.nickname || 'Seller pending'}</p><small>{deal.currency} · {deal.status.toLowerCase()}</small></div><i>›</i></button>) : <div className="empty-listings small"><span>🔒</span><h3>No private rooms yet</h3><p>Use Create room to start an official escrow request.</p></div>}</section>{notice && <p className="error">{notice}</p>}</main>;
}

function Room({ api, profile, deal, onBack }: { api: Props['api']; profile: any; deal: any; onBack: () => void }) {
  const [nickname, setNickname] = useState(''); const [draft, setDraft] = useState(''); const [messages, setMessages] = useState<any[]>([]); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const creatorRole = deal.buyer?.id === profile.id || deal.buyer?.nickname === profile.nickname ? 'BUYER' : 'SELLER';
  const hasCounterpart = Boolean(deal.buyer && deal.seller);
  const loadMessages = () => api(`/api/deals/${deal.id}/messages`).then(setMessages).catch(reason => setNotice((reason as Error).message));
  useEffect(() => { void loadMessages(); const timer = window.setInterval(() => void loadMessages(), 4000); return () => clearInterval(timer); }, [deal.id]);
  async function invite(event: FormEvent) { event.preventDefault(); setBusy(true); try { await api(`/api/deals/${deal.id}/invite-counterpart`, { method: 'POST', body: JSON.stringify({ nickname }) }); setNotice(`Invitation sent to @${nickname} in the Mini App.`); setNickname(''); } catch (reason) { setNotice((reason as Error).message); } finally { setBusy(false); } }
  async function admin() { setBusy(true); try { await api(`/api/deals/${deal.id}/request-admin`, { method: 'POST' }); setNotice('The official administrator has been notified in Telegram.'); } catch (reason) { setNotice((reason as Error).message); } finally { setBusy(false); } }
  async function send(event: FormEvent) { event.preventDefault(); if (!draft.trim()) return; setBusy(true); try { const message = await api(`/api/deals/${deal.id}/messages`, { method: 'POST', body: JSON.stringify({ message: draft }) }); setMessages(items => [...items, message]); setDraft(''); } catch (reason) { setNotice((reason as Error).message); } finally { setBusy(false); } }
  return <main className="dashboard deal-room"><header className="app-top"><button onClick={onBack}>‹</button><div className="top-brand"><span>🛡️</span><strong>Private Deal</strong></div><span className="room-status">{deal.status}</span></header><section className="deal-room-summary"><b>{deal.buyer?.nickname || 'Buyer pending'} ↔ {deal.seller?.nickname || 'Seller pending'}</b><p>{deal.terms}</p><small>{deal.currency} · official admin-controlled room</small></section><section className="room-actions">{!hasCounterpart && <form onSubmit={invite}><input value={nickname} onChange={event => setNickname(event.target.value)} placeholder={`Enter ${creatorRole === 'BUYER' ? 'seller' : 'buyer'} CL-Service username`} required /><button disabled={busy}>Invite</button></form>}<button className="admin-invite" onClick={admin} disabled={busy}>🛡️ Invite official admin</button></section><section className="private-message-list">{messages.map(message => <article className={message.sender.nickname === profile.nickname ? 'mine' : ''} key={message.id}><b>{message.sender.role === 'SUPER_ADMIN' ? '🛡️ Official Admin' : message.sender.nickname}</b><p>{message.body}</p></article>)}{!messages.length && <p className="chat-empty">Start the private conversation. Never send payment until the official administrator provides verified instructions.</p>}</section><form className="chat-composer" onSubmit={send}><input value={draft} onChange={event => setDraft(event.target.value)} placeholder="Write a message" maxLength={2000} /><button disabled={busy || !draft.trim()}>{busy ? '…' : 'Send'}</button></form>{notice && <p className={notice.includes('sent') || notice.includes('notified') ? 'success-note' : 'error'}>{notice}</p>}</main>;
}
