import { useEffect, useState, type FormEvent } from 'react';

type Props = { api: (path: string, options?: RequestInit) => Promise<any>; profile: any; onBack: () => void };

export function PrivateDeals({ api, profile, onBack }: Props) {
  const [deals, setDeals] = useState<any[]>([]);
  const [selected, setSelected] = useState<any>(null);
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState('');
  const load = async () => { try { const result = await api('/api/deals'); setDeals(result); const requestedId = new URLSearchParams(window.location.search).get('deal'); if (requestedId) setSelected(result.find((deal: any) => deal.id === requestedId) || null); } catch (reason) { setError((reason as Error).message); } };
  useEffect(() => { void load(); }, []);
  async function createRoom(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(''); const form = new FormData(event.currentTarget); try { const deal = await api('/api/private-deals', { method: 'POST', body: JSON.stringify({ role: form.get('role'), description: form.get('description'), amount: form.get('amount') || 0, currency: form.get('currency') || 'USD' }) }); setDeals(current => [deal, ...current]); setSelected(deal); setCreating(false); } catch (reason) { setError((reason as Error).message); } }
  if (selected) return <DealRoom api={api} profile={profile} deal={selected} onBack={() => { setSelected(null); void load(); }} />;
  return <main className="dashboard private-deals"><header className="app-top"><button onClick={onBack} aria-label="Back">‹</button><div className="top-brand"><span>🛡️</span><strong>Private Deals</strong></div><button onClick={() => setCreating(true)} aria-label="Create private deal">＋</button></header><section className="deal-intro"><div><span>OFFICIAL ESCROW</span><h1>Private deal rooms</h1><p>Invite your buyer or seller, then request the official administrator to join.</p></div><button onClick={() => setCreating(true)}>＋ Create room</button></section>{creating && <form className="room-form" onSubmit={createRoom}><h2>Create private room</h2><label>Your role<select name="role" defaultValue={profile.marketplaceRole || 'BUYER'}><option value="BUYER">Buyer</option><option value="SELLER">Seller</option></select></label><label>What is this deal about?<textarea name="description" minLength={10} maxLength={2000} placeholder="Describe the item or service, agreement, and why you need escrow." required /></label><div className="room-form-row"><label>Amount (optional)<input name="amount" type="number" min="0" step="0.01" placeholder="400" /></label><label>Currency<input name="currency" maxLength={3} defaultValue="USD" /></label></div><div><button type="button" className="secondary" onClick={() => setCreating(false)}>Cancel</button><button>Create room</button></div></form>}<section className="deal-list"><h2>Your deal rooms</h2>{deals.length ? deals.map(deal => <button className="deal-preview" onClick={() => setSelected(deal)} key={deal.id}><span>🛡️</span><div><b>{deal.item}</b><p>{deal.buyer?.nickname || 'Buyer pending'} · {deal.seller?.nickname || 'Seller pending'}</p><small>{deal.status.replaceAll('_', ' ').toLowerCase()}</small></div><i>›</i></button>) : <div className="empty-listings small"><span>🔒</span><h3>No private rooms yet</h3><p>Create a room, invite the other participant, then invite the official administrator.</p></div>}</section>{error && <p className="error">{error}</p>}</main>;
}

function DealRoom({ api, profile, deal, onBack }: { api: Props['api']; profile: any; deal: any; onBack: () => void }) {
  const [messages, setMessages] = useState<any[]>([]); const [draft, setDraft] = useState(''); const [counterpart, setCounterpart] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const isCreator = deal.buyer?.nickname === profile.nickname || deal.seller?.nickname === profile.nickname;
  const creatorRole = deal.buyer?.nickname === profile.nickname ? 'BUYER' : 'SELLER';
  const hasCounterpart = Boolean(deal.buyer && deal.seller);
  const loadMessages = async () => { try { setMessages(await api(`/api/deals/${deal.id}/messages`)); } catch (reason) { setError((reason as Error).message); } };
  useEffect(() => { void loadMessages(); const timer = window.setInterval(() => void loadMessages(), 4000); return () => window.clearInterval(timer); }, [deal.id]);
  async function send(event: FormEvent) { event.preventDefault(); if (!draft.trim() || busy) return; setBusy(true); try { const message = await api(`/api/deals/${deal.id}/messages`, { method: 'POST', body: JSON.stringify({ message: draft }) }); setMessages(current => [...current, message]); setDraft(''); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  async function inviteCounterpart(event: FormEvent) { event.preventDefault(); setBusy(true); try { await api(`/api/deals/${deal.id}/invite-counterpart`, { method: 'POST', body: JSON.stringify({ nickname: counterpart }) }); setError('Invitation sent in the Mini App.'); setCounterpart(''); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  async function inviteAdmin() { setBusy(true); try { await api(`/api/deals/${deal.id}/invite-admin`, { method: 'POST' }); setError('The official administrator was notified through the bot.'); } catch (reason) { setError((reason as Error).message); } finally { setBusy(false); } }
  return <main className="dashboard deal-room"><header className="app-top"><button onClick={onBack} aria-label="Back">‹</button><div className="top-brand"><span>🛡️</span><strong>Private Deal</strong></div><span className="room-status">{deal.status}</span></header><section className="deal-room-summary"><b>{deal.buyer?.nickname || 'Buyer pending'} ↔ {deal.seller?.nickname || 'Seller pending'}</b><p>{deal.terms}</p><small>Only the buyer, seller, and official administrator can access this room.</small></section>{isCreator && <section className="room-actions">{!hasCounterpart && <form onSubmit={inviteCounterpart}><input value={counterpart} onChange={event => setCounterpart(event.target.value)} placeholder={`Enter ${creatorRole === 'BUYER' ? 'seller' : 'buyer'} Mini App username`} required /><button disabled={busy}>Invite {creatorRole === 'BUYER' ? 'seller' : 'buyer'}</button></form>}<button className="admin-invite" onClick={inviteAdmin} disabled={busy}>🛡️ Invite official admin</button></section>}<section className="private-message-list">{messages.length ? messages.map(message => <article className={message.sender.nickname === profile.nickname ? 'mine' : ''} key={message.id}><b>{message.sender.role === 'SUPER_ADMIN' ? '🛡️ Official Admin' : message.sender.nickname}</b><p>{message.body}</p><small>{new Date(message.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</small></article>) : <p className="chat-empty">Start the private conversation. Do not send money until the official administrator confirms the escrow instructions.</p>}</section><form className="chat-composer" onSubmit={send}><input value={draft} onChange={event => setDraft(event.target.value)} placeholder="Write a message" maxLength={2000} /><button disabled={busy || !draft.trim()}>{busy ? '…' : 'Send'}</button></form>{error && <p className={error.includes('sent') || error.includes('notified') ? 'success-note' : 'error'}>{error}</p>}</main>;
}
