import { useEffect, useState, type FormEvent } from 'react';

type Api = (path: string, options?: RequestInit) => Promise<any>;
const tabs = ['Home', 'Catalog', 'Deals', 'Chat', 'Profile'];
const emojis = ['😀', '😂', '😍', '🔥', '👍', '👋', '🎉', '💬', '❤️', '✅', '🤝', '🔒', '🚀', '🙏', '👀', '✨', '😮', '😢', '😡', '🥳', '👏', '💯', '💪', '🤔', '🎯', '💬', '🌟', '☕', '📌', '🚫', '🫡', '💙'];

export function PublicChat({ api, onNavigate }: { api: Api; onNavigate: (view: string) => void }) {
  const [messages, setMessages] = useState<any[]>([]);
  const [draft, setDraft] = useState('');
  const [typers, setTypers] = useState<string[]>([]);
  const [emojiOpen, setEmojiOpen] = useState(false);
  const [sending, setSending] = useState(false);
  const [error, setError] = useState('');
  const [reactionMessageId, setReactionMessageId] = useState<string | null>(null);
  const [expandedReactions, setExpandedReactions] = useState(false);
  const load = async () => { try { setMessages(await api('/api/community/messages')); } catch (reason) { setError((reason as Error).message); } };
  useEffect(() => { void load(); const interval = window.setInterval(() => { void load(); void api('/api/community/typing').then(result => setTypers(result.users)).catch(() => undefined); }, 2200); return () => window.clearInterval(interval); }, []);
  function changeDraft(value: string) { setDraft(value); if (value.trim()) void api('/api/community/typing', { method: 'POST' }).catch(() => undefined); }
  async function send(event: FormEvent) { event.preventDefault(); if (!draft.trim() || sending) return; setSending(true); try { const message = await api('/api/community/messages', { method: 'POST', body: JSON.stringify({ message: draft }) }); setMessages(current => [...current, message]); setDraft(''); setEmojiOpen(false); } catch (reason) { setError((reason as Error).message); } finally { setSending(false); } }
  const addReaction = (emoji: string) => { setDraft(`${draft}${emoji}`); setReactionMessageId(null); setExpandedReactions(false); };
  return <main className="dashboard public-chat"><header className="app-top"><button onClick={() => onNavigate('Home')} aria-label="Open navigation">☰</button><div className="top-brand"><span>🔒</span><strong>Community Chat</strong></div><button onClick={() => void load()} aria-label="Refresh chat">↻</button></header><section className="chat-heading"><div><h1>CL-Service Community</h1><p>Public chat for registered members</p></div><span>● Live</span></section><p className="chat-security">Community messages are server-stored. Never share payment data, recovery codes, or private details.</p><section className="message-list">{messages.length ? messages.map(message => <article className={reactionMessageId === message.id ? 'reaction-selected' : ''} onClick={() => { setReactionMessageId(message.id); setExpandedReactions(false); }} key={message.id}><span className="chat-avatar">{message.sender.nickname[0].toUpperCase()}</span><div><b>{message.sender.nickname}</b><small>{new Date(message.createdAt).toLocaleString()}</small><p>{message.body}</p>{reactionMessageId === message.id && <div className="reaction-tray" onClick={event => event.stopPropagation()}>{(expandedReactions ? emojis : emojis.slice(0, 6)).map(emoji => <button type="button" onClick={() => addReaction(emoji)} key={emoji}>{emoji}</button>)}<button className="more-reactions" type="button" onClick={() => setExpandedReactions(value => !value)}>{expandedReactions ? '−' : '+'}</button></div>}</div></article>) : <div className="empty-listings small"><span>💬</span><h3>Start the conversation</h3><p>Say hello to the CL-Service community.</p></div>}</section>{typers.length > 0 && <p className="typing-indicator">{typers.join(', ')} {typers.length === 1 ? 'is' : 'are'} typing…</p>}{emojiOpen && <div className="emoji-tray">{emojis.map(emoji => <button type="button" onClick={() => changeDraft(`${draft}${emoji}`)} key={emoji}>{emoji}</button>)}</div>}<form className="chat-composer" onSubmit={send}><button className="emoji-button" type="button" onClick={() => setEmojiOpen(value => !value)} aria-label="Open emojis">☺</button><input value={draft} onChange={event => changeDraft(event.target.value)} placeholder="Write a message" maxLength={1000} /><button disabled={sending || !draft.trim()}>{sending ? '…' : 'Send'}</button></form><nav className="bottom-nav five-tabs">{tabs.map(tab => <button className={tab === 'Chat' ? 'active' : ''} onClick={() => onNavigate(tab)} key={tab}><span>{tab === 'Home' ? '⌂' : tab === 'Catalog' ? '▦' : tab === 'Deals' ? '◇' : tab === 'Chat' ? '▢' : '♙'}</span><small>{tab}</small></button>)}</nav>{error && <p className="error">{error}</p>}</main>;
}
